services:
  - type: web
    name: gemini-fastapi
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter  # 可选择 starter, standard, pro
    region: oregon  # 或 singapore, frankfurt 等
    branch: main
    healthCheckPath: /health
    envVars:
      - key: CONFIG_SERVER__HOST
        value: "0.0.0.0"
      - key: CONFIG_SERVER__PORT
        value: "8000"
      - key: CONFIG_SERVER__API_KEY
        sync: false  # 在 Render 控制台中手动设置
      # Gemini客户端配置 - 可以在Render控制台中动态添加任意数量的客户端
      # 格式: CONFIG_GEMINI__CLIENTS__[索引]__[字段名]
      # 示例: CONFIG_GEMINI__CLIENTS__0__ID, CONFIG_GEMINI__CLIENTS__0__SECURE_1PSID 等
      # 注意：这里不需要预先定义，可以直接在Render控制台的Environment页面添加
      # 其他配置
      - key: CONFIG_GEMINI__TIMEOUT
        value: "60"
      - key: CONFIG_GEMINI__AUTO_REFRESH
        value: "true"
      - key: CONFIG_STORAGE__PATH
        value: "/opt/render/project/src/data/lmdb"
      - key: CONFIG_STORAGE__MAX_SIZE
        value: "134217728"  # 128MB
      - key: CONFIG_LOGGING__LEVEL
        value: "INFO"

  # 可选：添加数据库服务（如果需要更强的持久化）
  # - type: redis
  #   name: gemini-cache
  #   plan: starter
  #   maxmemoryPolicy: allkeys-lru 